### PR TITLE
Activity dashboard fixes

### LINKED ISSUE #777: Fix activity dashboard pluralization
image

Right now the dashboard is rendering text like `1 months`, when it should be `1 month`. It should be fixed for all cases, including `weeks` and `days`

### LINKED ISSUE #778: Last month activity data not rendered on activity dashboard
It looks like all charts on the activity dashboard are showing 0 for the last month:

image

looking at the API response for `napari-svg`, I found that the response is not returning any data for the last month:
https://api.staging.napari-hub.org/metrics/napari-svg

```
10/2021: 9479
11/2021: 9848
12/2021: 9822
01/2022: 10623
02/2022: 15903
03/2022: 12975
04/2022: 12467
05/2022: 16457
06/2022: 10865
07/2022: 10982
08/2022: 8854
09/2022: 10298
```

### LINKED ISSUE #779: Activity showing multiple 0s on y-axis
It should only be showing one 0

image

### PR DESCRIPTION
**Pull request by codemonkey800**
## Description

Closes #777
Closes #778 
Closes #779

### Fix pluralization

image

image

### Fix last month always rendering 0

image

### Fix all multiple 0s on y-axis

image

### CODE REVIEW

**Review by richaagarwal — APPROVED** [review]
🙌🏽

File: frontend/src/components/ActivityDashboard/InstallsText.tsx [hunk 1]
```diff
@@ -0,0 +1,21 @@
+import Skeleton from '@mui/material/Skeleton';
+import { useTranslation } from 'next-i18next';
+
+import { useFormattedNumber } from '@/hooks';
+
+interface Props {
+  installs?: number;
```
Comment (klai95) [inline frontend/src/components/ActivityDashboard/InstallsText.tsx:7]: Just want to make sure, `installs` is optional because some plugins don't have install data for a given month right? @codemonkey800

**Review by klai95 — APPROVED** [review]
LGTM! Left one clarifying comment!

File: frontend/src/components/ActivityDashboard/ActivityUsageSection.tsx [hunk 2]
```diff
@@ -9,7 +9,7 @@ export function ActivityUsageSection() {
   const [t] = useTranslation(['activity']);
 
   return (
-    <ActivitySection title={t('activity:usage')}>
+    <ActivitySection className="min-h-[200px]" title={t('activity:usage')}>
```
Comment (manasaV3) [inline frontend/src/components/ActivityDashboard/ActivityUsageSection.tsx:12]: Does the `[200px]` do some magic underneath the hood or is it a WYSIWYG? 😁

**Review by manasaV3 — APPROVED** [review]
