### PR TITLE
Disables highlighting for `Supported data`

### LINKED ISSUE #394: Preview page shows the same fields for two sections
#### Description
The top header of the preview page shows Name, Summary, Description & Authors for both "Describe what the plugin does" *and* "Tell users where they can get help".

#### Steps/Code to Reproduce
See any PR with a preview e.g. [this one](https://github.com/DragaDoncila/default-wout-github/pull/1#issuecomment-1017917612)

image

#### Expected Results
I suspect we want the "Project URLs" section in there?

### PR DESCRIPTION
**Pull request by codemonkey800**
## Description

Closes #394

This disables highlighting for the `Support data` metadata:

image

### CODE REVIEW

File: frontend/src/components/PluginDetails/PluginMetadata.tsx [hunk 1]
```diff
@@ -140,8 +157,8 @@ function PluginMetadataBase({
       className="h-56"
       render={() => (
         <>
-          {renderSingleItemList('version')}
-          {renderSingleItemList('releaseDate')}
+          {renderSingleItemList('version', { highlight: false })}
```
Comment (potating-potato) [inline frontend/src/components/PluginDetails/PluginMetadata.tsx:160]: is this change relevant to the supported data field?

**Review by potating-potato — COMMENTED** [review]
1 question otherwise LGTM

File: frontend/src/components/PluginDetails/PluginMetadata.tsx (hunk 1 above)
Comment (codemonkey800) [reply frontend/src/components/PluginDetails/PluginMetadata.tsx:160]: It's not, but these fields should not be highlighted since we don't show them in the missing metadata fields

**Review by potating-potato — APPROVED** [review]

**Comment by potating-potato** [comment]
hmm should this close #393?

**Comment by codemonkey800** [comment]
dang it, i was off by one number 😢 yes it should be closing that issue lol
